---
title: "Untitled"
author: "Vincent Pancini"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Example 1 - Tract using tidycensus
```{r message = FALSE, warning = FALSE, echo = FALSE}
# install.packages(c("tidyverse", "tidycensus", "tigris", "sf"))
library(tidyverse)
library(tidycensus)

# Retrieve data
tc_tracts <- tidycensus::get_acs(geography = "tract",
                                 variables = c(medincome = "B19013_001"),
                                 state = "VA",
                                 county = "Fairfax County",
                                 year = 2019,
                                 geometry = TRUE)

# Create map
tract_tidycensus <- ggplot() +
  geom_sf(data = tc_tracts,
          aes(fill = estimate)) +
  scale_fill_gradientn(labels = scales::dollar,
                       colors = my_colors) +
  labs(title = "Median income income in Fairfax County, VA by census tract ",
       fill = "Median Income") +
  theme_void()

ggsave("tract_tidycensus.png", plot = tract_tidycensus, width = 8, height = 5, units = "in")
```

# Example 2 - ZCTA using tidycensus
```{r message = FALSE, warning = FALSE, echo = FALSE}
# install.packages(c("tidyverse", "tidycensus", "tigris", "sf"))
library(tidyverse)
library(tidycensus)

# Retrieve data
tc_zcta <- tidycensus::get_acs(geography = "zcta",
                               variables = c(medincome = "B19013_001"),
                               state = "VA",
                               year = 2019,
                               geometry = TRUE)

# Create map
zcta_tidycensus <- ggplot() +
  geom_sf(data = tc_zcta,
          aes(fill = estimate)) +
  scale_fill_gradientn(labels = scales::dollar,
                       colors = my_colors) +
  labs(title = "Median income in Fairfax County, VA by ZCTA",
       fill = "Median Income") +
  theme_void()

ggsave("zcta_tidycensus.png", plot = zcta_tidycensus, width = 8, height = 5, units = "in")
```

# Example 3 - PUMA using tidycensus
```{r message = FALSE, warning = FALSE, echo = FALSE}
# install.packages(c("tidyverse", "tidycensus", "tigris", "sf"))
library(tidyverse)
library(tidycensus)

tc_puma <- tidycensus::get_acs(geography = "public use microdata area",
                               variables = c(medincome = "B19013_001"),
                               state = "VA",
                               year = 2019,
                               geometry = TRUE)

# create map
puma_tidycensus <- ggplot() +
  geom_sf(data = tc_puma,
          aes(fill = estimate)) +
  scale_fill_gradientn(labels = scales::dollar,
                       colors = my_colors) +
  labs(title = "Median income in Fairfax County, VA by PUMA",
       fill = "Median Income") +
  theme_void()

ggsave("puma_tidycensus.png", plot = puma_tidycensus, width = 8, height = 5, units = "in")
```

# Example 4 - PUMA and loading in original data
```{r message = FALSE, warning = FALSE}
# install.packages(c("tidyverse", "tidycensus", "tigris", "sf"))
library(tidyverse)
library(tigris)
library(sf)

# pull the spatial data from (tigris)
pumas <- tigris::pumas(state = "OH", year = 2019, cb = TRUE) %>%
  rename(puma = PUMACE10) %>%
  transmute(puma = as.numeric(puma))
## the `year` argument defaults to 2020, but cartographic boundary PUMAs are not yet available for years after 2019, so use the argument `year = 2019` instead to request your data.
## TIGER/Line shapefiles are high-resolution and follow legal boundaries. Their larger size slows down processing time, and because they follow legal boundaries, some objects like bodies of water will not be visible. Cartographic boundary files are quicker to download and follow the US coastline, which better aligns with maps that we're used to looking at. The argument `cb = TRUE` pulls the cartographic boundary files, but setting the argument to `cb = FALSE` will pull the TIGER line files.

# load in original data
ss_inc <- read_csv(here::here("mean_ssinc_oh_2019.csv"))

# join the puma shapefiles to our original puma-level data so we can map it
ss_inc_puma <- left_join(pumas, ss_inc, by = "puma")

# we have data for the entire state, but we only want to map Franklin County.
# first get county shapefiles for the state of Ohio
ohio <- tigris::counties(state = "OH", year = 2019, cb = TRUE)

# now we can join the pumas to counties, and then filter to the county we're interested in
my_data <- sf::st_join(ss_inc_puma, ohio, join = st_intersects) %>%
  filter(COUNTYFP == "049")

# and finally, we can create a map
puma_own_data <- ggplot() +
  geom_sf(data = my_data,
          aes(fill = mean_ssinc),
          color = "black",
          size = 0.2) +
  scale_fill_gradient(high = "#132B43", low = "#56B1F7",
                      labels = scales::dollar,
                      #trans = 'reverse'
  ) +
  labs(title = "Mean Social Security Income in Franklin County, OH, by PUMA",
       fill = "Mean SSI") +
  theme_void()

ggplot2::ggsave("puma_own_data.png", plot = puma_own_data, width = 8, height = 8, units = "in")
```
